_target_: src.models.embryo_module.EmbryoLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.00005
  weight_decay: 0.001

scheduler:
  _target_: torch.optim.lr_scheduler.ExponentialLR
  _partial_: true
  gamma: 0.98

net:
  _target_: src.models.components.efficientnetb0.EfficientNetB0
  output_size: 2
  pretrained: true
  frozen: true

weight: [1.0, 1.5]

# compile model for faster training with pytorch 2.0
compile: false
