# @package _global_

defaults:
  - _self_
  - data: mnist
  - model: mnist
  - logger: null
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: ???
data_dir: data/world-championship-2023-embryo-classification/hvwc23
